### ISSUE TITLE
Fix submission deadlocks

### ISSUE THREAD

**Issue by SuprDewd** [SuprDewd/epsilon#14]
If an error occurs after a submission has been checked out for judging, it stays unjudged forever. This was introduced in f4231506.

**Comment by jamiees2** [comment]
This should be fixed now. Any unhandled exceptions are caught by `with` which takes care to restore the submissionqueue object if possible. If that is not enough, then it also considers any queue objects which were last dequeued 10 minutes ago or greater, and reprocesses them.
