### ISSUE TITLE
UnicodeDecodeError, invalid continuation byte

### ISSUE THREAD

**Issue by SuprDewd** [SuprDewd/epsilon#6]
I've seen this error come up once or twice. The DrJava editor was probably doing something rotten with the text file that was being submitted. But the server should still be able to handle it somehow.

**Comment by jamiees2** [comment]
This is most likely fixed in 8f4fc85. The server should be able to detect most encodings and it will then convert them to UTF-8 before saving in the DB. The encoding detection is dependent on `chardet` though, which may not neccessarily always detect the correct encoding.
