### ISSUE TITLE
Use isolate

### ISSUE THREAD

**Issue by SuprDewd** [SuprDewd/epsilon#9]
We should replace jailkit/safeexec with [isolate](https://github.com/cms-dev/cms/tree/master/isolate). It seems to be much easier to set up and use, and just looks much nicer than the current jailing mechanism.

**Comment by jamiees2** [comment]
That link 404's, this works: [isolate](https://github.com/cms-dev/isolate)

**Comment by jamiees2** [comment]
Resolved in 100b9efb4dfa378e0e887253e381e57275df1002
